### ISSUE TITLE
Job retry and max_retries?

### ISSUE THREAD

**Issue by triptec** [akira/exq#95] opened 2015-10-07 08:46 UTC
I'm wondering if it's possible to set Job retry and max retries when enqueuing jobs?

**Comment by akira** [comment] 2015-10-07 08:53
Retry facility is not yet implemented, would like to add that as soon as possible though - see issue #22.

**Comment by triptec** [comment] 2015-10-07 09:09
Ok, currently I've got a queue with concurrency: 1, when a job failes and the worker terminates, there's not another worker started, is this correct?

**Comment by akira** [comment] 2015-10-08 07:03
Yes correct, that particular ```job``` will fail and will not be retried currently. This can be implemented by adding some extra data to the job regarding retries needed and current retry count.  Then adding extra logic to:

https://github.com/akira/exq/blob/master/lib/exq/worker/server.ex#L59

To retry them and update retry count. 

Also, not sure if you are asking about the ```worker``` itself, this job failing will not prevent future jobs from working.  

I am currently on vacation, but I can prioritize looking at a simple retry mechanism when I get back next week.

**Comment by triptec** [comment] 2015-10-08 09:43
Please don't prioritize retry on my behalf if there's more urgent things.
About the worker, mind you this happend once. A failed job, a timeout I believe crached the job and I think the worker and no other jobs where picked up, so I started another instance and it started working off the queue.

I'll get back if this wasn't a isolated event.

**Comment by akira** [comment] 2015-11-01 20:43
Duplicate of #22

**Closed by akira** 2015-11-01 20:43 UTC
